name: today
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.1
  sqflite: ^2.0.0+4
  intl: ^0.17.0
  path: ^1.8.0
  moor_flutter: ^4.0.0
  flutter_slidable: ^0.6.0
  moor: ^4.6.1
  flutter_bloc: ^7.3.3
  bloc: ^7.2.1
  equatable: ^2.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  moor_generator: ^4.6.0
  build_runner: ^2.1.4



flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #